version: '3.1'

services:
  db-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  db-redis:
      image: redis
      ports:
      - "6379:6379"